version: '3.8'

services:
  app:
    container_name: taskify_api
    build: .
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run start:dev
    networks:
      - taskify_network

  db:
    container_name: postgres_db
    image: postgres:15
    ports:
      - "15432:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-postgres} 
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres} 
      - POSTGRES_DB=${POSTGRES_DB:-taskify}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - taskify_network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres} -d ${POSTGRES_DB:-taskify}" ]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:


networks:
  taskify_network:
    driver: bridge
